# Use postgres/example user/password credentials
version: '3.7'
services:
    postgres:
        image: postgres:10.6
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=agora
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '8088:5432'
        volumes: 
          # - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
          - ./postgres:/var/lib/postgresql/data

